name: Auth Server CI/CD for Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: qr-attendance-455219
  SERVICE_NAME: auth-server
  REGION: us-central1
  ARTIFACT_REGISTRY: gcr.io
  SERVICE_ACCOUNT: github-action@qr-attendance-455219.iam.gserviceaccount.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_AUTH}}
      
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.ARTIFACT_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }},${{ env.ARTIFACT_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest
      
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.ARTIFACT_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: |
            --platform=managed
            --allow-unauthenticated
            --memory=512Mi
            --cpu=1
            --min-instances=1
            --no-cpu-throttling
            --timeout=300s
            --port=8080
            --service-account=${{ env.SERVICE_ACCOUNT }}
          env_vars: |
            FRONTEND_URL=https://qr-attendance-1043677821736.us-central1.run.app
            GOOGLE_CLIENT_ID=1043677821736-sd578og9up9kkobht663q1dchucsrhep.apps.googleusercontent.com
            GOOGLE_CLIENT_SECRET=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
      
      - name: Show Auth Server URL
        run: |
          echo "Auth Server URL: ${{ steps.deploy.outputs.url }}"
          echo "Auth Server successfully deployed to Cloud Run"