name: Auth Server CI/CD for App Engine

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  PROJECT_ID: qr-attendance-455219
  REGION: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: cd AuthServer && ./mvnw clean package -DskipTests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: cd AuthServer && ./mvnw clean package -DskipTests
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_AUTH }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
    
    - name: Enable required APIs
      run: |
        # Enable required APIs
        gcloud services enable appengine.googleapis.com --quiet || true
        gcloud services enable cloudbuild.googleapis.com --quiet || true
        gcloud services enable firestore.googleapis.com --quiet || true
    
    - name: Create app.yaml
      run: |
        cd AuthServer
        mkdir -p src/main/appengine
        cat > src/main/appengine/app.yaml << 'EOF'
        runtime: java17
        instance_class: F2
        
        env_variables:
          SPRING_PROFILES_ACTIVE: 'production'
          GOOGLE_CLIENT_ID: '1043677821736-sd578og9up9kkobht663q1dchucsrhep.apps.googleusercontent.com'
          GOOGLE_CLIENT_SECRET: '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'
        
        handlers:
          - url: /.*
            script: auto
            secure: always
        
        automatic_scaling:
          min_instances: 1
          max_instances: 5
          min_idle_instances: 1
          max_idle_instances: 2
          target_cpu_utilization: 0.65
          target_throughput_utilization: 0.65
          max_concurrent_requests: 50
        EOF
    
    - name: Deploy to App Engine
      run: |
        cd AuthServer
        gcloud app deploy src/main/appengine/app.yaml --project=${{ env.PROJECT_ID }} --quiet
    
    - name: Show deployment URL
      run: |
        echo "Auth Server URL: https://${{ env.PROJECT_ID }}.uc.r.appspot.com"
        echo "Auth Server deployed to App Engine"