on:
  push:
    branches:
      - '**'

jobs:
  docker-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Docker compose config
        run: docker compose config
      - name: Verify Dockerfile
        run: |
          DOCKERFILE=Dockerfile
          if [[ ! -f "$DOCKERFILE" ]]; then
            echo "❌ Dockerfile not found!"
            exit 1
          fi
      
          # Check number of stages
          STAGE_COUNT=$(grep -c '^FROM' "$DOCKERFILE")
          echo "✅ Found $STAGE_COUNT stages in the Dockerfile."
          if [[ $STAGE_COUNT -lt 2 ]]; then
            echo "❌ Dockerfile must have at least 2 stages (multi-stage build required)."
            exit 1
          fi
      
          # Check base image
          if ! grep -q '^FROM python:3.11-slim' "$DOCKERFILE"; then
            echo "❌ Base image is not 'python:3.11-slim'"
            exit 1
          else
            echo "✅ Base image is 'python:3.11-slim'"
          fi
      
          # Check WORKDIR
          if ! grep -q '^WORKDIR /app' "$DOCKERFILE"; then
            echo "❌ WORKDIR is not set to '/app'"
            exit 1
          else
            echo "✅ WORKDIR is set to '/app'"
          fi

  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # checkout code
      - uses: actions/checkout@v4

      # authenticate with GCP with workload identity provider
      - uses: 'google-github-actions/auth@v2'
        id: auth
        name: Authenticate to GCP
        with:
          project_id: 'qr-attendance-455219' # update with your project ID
          workload_identity_provider: 'projects/1043677821736/locations/global/workloadIdentityPools/github/providers/my-repo' # update with your Workload Identity Pool

      # configure/login with docker
      - name: gcloud Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # setup docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # build and push the image
      - name: Set short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            us-central1-docker.pkg.dev/qr-attendance-455219/qr-attendance/app:${{ env.SHORT_SHA }}
            us-central1-docker.pkg.dev/qr-attendance-455219/qr-attendance/app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy qr-attendance \
            --allow-unauthenticated \
            --image us-central1-docker.pkg.dev/qr-attendance-455219/qr-attendance/app:${{ env.SHORT_SHA }} \
            --service-account qr-attendance@qr-attendance-455219.iam.gserviceaccount.com \
            --region us-central1 \
            --port 8000
